# Generated by Django 4.2.2 on 2023-06-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('dep', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=2550)),
                ('nationality', models.CharField(max_length=255)),
                ('rel', models.CharField(max_length=255)),
            ],
        ),
    ]
